export { default as Hero } from './Hero'
export { default as Navbar } from './Navbar'
export { default as About } from './About'
export { default as Gallery } from './Gallery'
export { default as News } from './News'
export { default as Socials } from './Socials'
export { default as Footer } from './Footer'
export { default as Pet } from './Pet'